project:
  name: Strawberry Bench / Countries
  id: r3-bench
  description: Benchmarks on listing countries starting with B that don't have E in their name

meta:
  # Global checklist for all tasks
  checklist:
    - Answer doesn't have Brunei in the countries list
    - Answer doesn't have Bangladesh in the countries list
    - |
      Answer contains these 10 countries:
      - Bahamas
      - Bahrain
      - Barbados
      - Bhutan
      - Bolivia
      - Botswana
      - Brazil
      - Bulgaria
      - Burkina Faso
      - Burundi

  # Global repeat / rephrase
  repeat: 10
  rephrase: true

tasks:
  - id: gpt-4o-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openai/gpt-4o-2024-08-06

  - id: gpt-4o-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openai/gpt-4o-2024-11-20

  - id: gpt-4o-mini-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openai/gpt-4o-mini-2024-07-18

  - id: llama-3.3-70b-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openrouter/meta-llama/llama-3.3-70b-instruct

  - id: llama-3.1-405b-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openrouter/meta-llama/llama-3.1-405b-instruct

  - id: deepseek-r1-distill-llama-70b-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openrouter/deepseek/deepseek-r1-distill-llama-70b
      params:
        timeout: 30

  # HEAVY RATE LIMITS
  - id: gemini-2.0-flash-thinking-exp-free-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openrouter/google/gemini-2.0-flash-thinking-exp:free
      params:
        timeout: 30

  - id: gemini-flash-1.5-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openrouter/google/gemini-flash-1.5

  - id: gemini-2.0-flash-exp-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: gemini/gemini-2.0-flash-exp

  - id: gemini-2.0-flash-thinking-exp-01-21-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: gemini-v1alpha/gemini-2.0-flash-thinking-exp-01-21

  - id: deepseek-chat-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openrouter/deepseek/deepseek-chat
      params:
        timeout: 30

  - id: o1-mini-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openai/o1-mini-2024-09-12

  - id: o3-mini-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openai/o3-mini-2025-01-31
      params:
        reasoning_effort: low

  - id: o3-mini-high-effort-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openai/o3-mini-2025-01-31
      params:
        reasoning_effort: high

  - id: o1-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openai/o1
      params:
        reasoning_effort: low
  
  - id: o1-high-effort-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openai/o1-2024-12-17
      params:
        reasoning_effort: high

  - id: deepseek-r1-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openrouter/deepseek/deepseek-r1
      params:
        extra_body:
          include_reasoning: true

  - id: grok-2-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: xai/grok-2-1212

  - id: sonnet-3.7-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: anthropic/claude-3-7-sonnet-20250219

  - id: sonnet-3.7-thinking-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: anthropic/claude-3-7-sonnet-20250219
      params:
        thinking: {type: enabled, budget_tokens: 4000}
        max_tokens: 8000

  - id: sonnet-3.5-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: anthropic/claude-3-5-sonnet-20241022

  - id: claude-3-opus-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: anthropic/claude-3-opus-20240229

  - id: claude-3-5-haiku-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: anthropic/claude-3-5-haiku-20241022

  - id: mistral-large-2411-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openrouter/mistralai/mistral-large-2411

  - id: qwen-max-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: openrouter/qwen/qwen-max

  - id: gemini-2.0-pro-exp-02-05-countries
    input:
      question: Write a list of all country names starting with the letter B, which don't have a letter E in their name.
      model: gemini-v1alpha/gemini-2.0-pro-exp-02-05
      extra:
        delay: 30 # 2 RPM limit
